/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Catch Up` | `/Catch Up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Live` | `/Live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/podcast` | `/podcast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Catch Up` | `/Catch Up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/feedback` | `/feedback`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Live` | `/Live`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/podcast` | `/podcast`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Catch Up${`?${string}` | `#${string}` | ''}` | `/Catch Up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/feedback${`?${string}` | `#${string}` | ''}` | `/feedback${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Live${`?${string}` | `#${string}` | ''}` | `/Live${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/podcast${`?${string}` | `#${string}` | ''}` | `/podcast${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trending${`?${string}` | `#${string}` | ''}` | `/trending${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Catch Up` | `/Catch Up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Live` | `/Live`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/podcast` | `/podcast`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trending` | `/trending`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
